// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDistributionParamsParams creates a new DistributionParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDistributionParamsParams() *DistributionParamsParams {
	return &DistributionParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDistributionParamsParamsWithTimeout creates a new DistributionParamsParams object
// with the ability to set a timeout on a request.
func NewDistributionParamsParamsWithTimeout(timeout time.Duration) *DistributionParamsParams {
	return &DistributionParamsParams{
		timeout: timeout,
	}
}

// NewDistributionParamsParamsWithContext creates a new DistributionParamsParams object
// with the ability to set a context for a request.
func NewDistributionParamsParamsWithContext(ctx context.Context) *DistributionParamsParams {
	return &DistributionParamsParams{
		Context: ctx,
	}
}

// NewDistributionParamsParamsWithHTTPClient creates a new DistributionParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDistributionParamsParamsWithHTTPClient(client *http.Client) *DistributionParamsParams {
	return &DistributionParamsParams{
		HTTPClient: client,
	}
}

/* DistributionParamsParams contains all the parameters to send to the API endpoint
   for the distribution params operation.

   Typically these are written to a http.Request.
*/
type DistributionParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the distribution params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistributionParamsParams) WithDefaults() *DistributionParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the distribution params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DistributionParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the distribution params params
func (o *DistributionParamsParams) WithTimeout(timeout time.Duration) *DistributionParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the distribution params params
func (o *DistributionParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the distribution params params
func (o *DistributionParamsParams) WithContext(ctx context.Context) *DistributionParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the distribution params params
func (o *DistributionParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the distribution params params
func (o *DistributionParamsParams) WithHTTPClient(client *http.Client) *DistributionParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the distribution params params
func (o *DistributionParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DistributionParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
