// Code generated by go-swagger; DO NOT EDIT.

package treasury

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTreasuryTaxCapsParams creates a new GetTreasuryTaxCapsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTreasuryTaxCapsParams() *GetTreasuryTaxCapsParams {
	return &GetTreasuryTaxCapsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTreasuryTaxCapsParamsWithTimeout creates a new GetTreasuryTaxCapsParams object
// with the ability to set a timeout on a request.
func NewGetTreasuryTaxCapsParamsWithTimeout(timeout time.Duration) *GetTreasuryTaxCapsParams {
	return &GetTreasuryTaxCapsParams{
		timeout: timeout,
	}
}

// NewGetTreasuryTaxCapsParamsWithContext creates a new GetTreasuryTaxCapsParams object
// with the ability to set a context for a request.
func NewGetTreasuryTaxCapsParamsWithContext(ctx context.Context) *GetTreasuryTaxCapsParams {
	return &GetTreasuryTaxCapsParams{
		Context: ctx,
	}
}

// NewGetTreasuryTaxCapsParamsWithHTTPClient creates a new GetTreasuryTaxCapsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTreasuryTaxCapsParamsWithHTTPClient(client *http.Client) *GetTreasuryTaxCapsParams {
	return &GetTreasuryTaxCapsParams{
		HTTPClient: client,
	}
}

/* GetTreasuryTaxCapsParams contains all the parameters to send to the API endpoint
   for the get treasury tax caps operation.

   Typically these are written to a http.Request.
*/
type GetTreasuryTaxCapsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get treasury tax caps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTreasuryTaxCapsParams) WithDefaults() *GetTreasuryTaxCapsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get treasury tax caps params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTreasuryTaxCapsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) WithTimeout(timeout time.Duration) *GetTreasuryTaxCapsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) WithContext(ctx context.Context) *GetTreasuryTaxCapsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) WithHTTPClient(client *http.Client) *GetTreasuryTaxCapsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get treasury tax caps params
func (o *GetTreasuryTaxCapsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTreasuryTaxCapsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
