// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStakingParamsParams creates a new StakingParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStakingParamsParams() *StakingParamsParams {
	return &StakingParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStakingParamsParamsWithTimeout creates a new StakingParamsParams object
// with the ability to set a timeout on a request.
func NewStakingParamsParamsWithTimeout(timeout time.Duration) *StakingParamsParams {
	return &StakingParamsParams{
		timeout: timeout,
	}
}

// NewStakingParamsParamsWithContext creates a new StakingParamsParams object
// with the ability to set a context for a request.
func NewStakingParamsParamsWithContext(ctx context.Context) *StakingParamsParams {
	return &StakingParamsParams{
		Context: ctx,
	}
}

// NewStakingParamsParamsWithHTTPClient creates a new StakingParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewStakingParamsParamsWithHTTPClient(client *http.Client) *StakingParamsParams {
	return &StakingParamsParams{
		HTTPClient: client,
	}
}

/* StakingParamsParams contains all the parameters to send to the API endpoint
   for the staking params operation.

   Typically these are written to a http.Request.
*/
type StakingParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the staking params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StakingParamsParams) WithDefaults() *StakingParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the staking params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StakingParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the staking params params
func (o *StakingParamsParams) WithTimeout(timeout time.Duration) *StakingParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the staking params params
func (o *StakingParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the staking params params
func (o *StakingParamsParams) WithContext(ctx context.Context) *StakingParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the staking params params
func (o *StakingParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the staking params params
func (o *StakingParamsParams) WithHTTPClient(client *http.Client) *StakingParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the staking params params
func (o *StakingParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StakingParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
