// Code generated by go-swagger; DO NOT EDIT.

package staking

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1StakingValidatorsOperatorAddrParams creates a new GetV1StakingValidatorsOperatorAddrParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1StakingValidatorsOperatorAddrParams() *GetV1StakingValidatorsOperatorAddrParams {
	return &GetV1StakingValidatorsOperatorAddrParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1StakingValidatorsOperatorAddrParamsWithTimeout creates a new GetV1StakingValidatorsOperatorAddrParams object
// with the ability to set a timeout on a request.
func NewGetV1StakingValidatorsOperatorAddrParamsWithTimeout(timeout time.Duration) *GetV1StakingValidatorsOperatorAddrParams {
	return &GetV1StakingValidatorsOperatorAddrParams{
		timeout: timeout,
	}
}

// NewGetV1StakingValidatorsOperatorAddrParamsWithContext creates a new GetV1StakingValidatorsOperatorAddrParams object
// with the ability to set a context for a request.
func NewGetV1StakingValidatorsOperatorAddrParamsWithContext(ctx context.Context) *GetV1StakingValidatorsOperatorAddrParams {
	return &GetV1StakingValidatorsOperatorAddrParams{
		Context: ctx,
	}
}

// NewGetV1StakingValidatorsOperatorAddrParamsWithHTTPClient creates a new GetV1StakingValidatorsOperatorAddrParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1StakingValidatorsOperatorAddrParamsWithHTTPClient(client *http.Client) *GetV1StakingValidatorsOperatorAddrParams {
	return &GetV1StakingValidatorsOperatorAddrParams{
		HTTPClient: client,
	}
}

/* GetV1StakingValidatorsOperatorAddrParams contains all the parameters to send to the API endpoint
   for the get v1 staking validators operator addr operation.

   Typically these are written to a http.Request.
*/
type GetV1StakingValidatorsOperatorAddrParams struct {

	/* Account.

	   User address
	*/
	Account *string

	/* OperatorAddr.

	   Operator address
	*/
	OperatorAddr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 staking validators operator addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1StakingValidatorsOperatorAddrParams) WithDefaults() *GetV1StakingValidatorsOperatorAddrParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 staking validators operator addr params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1StakingValidatorsOperatorAddrParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) WithTimeout(timeout time.Duration) *GetV1StakingValidatorsOperatorAddrParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) WithContext(ctx context.Context) *GetV1StakingValidatorsOperatorAddrParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) WithHTTPClient(client *http.Client) *GetV1StakingValidatorsOperatorAddrParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) WithAccount(account *string) *GetV1StakingValidatorsOperatorAddrParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) SetAccount(account *string) {
	o.Account = account
}

// WithOperatorAddr adds the operatorAddr to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) WithOperatorAddr(operatorAddr string) *GetV1StakingValidatorsOperatorAddrParams {
	o.SetOperatorAddr(operatorAddr)
	return o
}

// SetOperatorAddr adds the operatorAddr to the get v1 staking validators operator addr params
func (o *GetV1StakingValidatorsOperatorAddrParams) SetOperatorAddr(operatorAddr string) {
	o.OperatorAddr = operatorAddr
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1StakingValidatorsOperatorAddrParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Account != nil {

		// query param account
		var qrAccount string

		if o.Account != nil {
			qrAccount = *o.Account
		}
		qAccount := qrAccount
		if qAccount != "" {

			if err := r.SetQueryParam("account", qAccount); err != nil {
				return err
			}
		}
	}

	// path param operatorAddr
	if err := r.SetPathParam("operatorAddr", o.OperatorAddr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
