// Code generated by go-swagger; DO NOT EDIT.

package governance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1GovProposalsProposalIDDepositsParams creates a new GetV1GovProposalsProposalIDDepositsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1GovProposalsProposalIDDepositsParams() *GetV1GovProposalsProposalIDDepositsParams {
	return &GetV1GovProposalsProposalIDDepositsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1GovProposalsProposalIDDepositsParamsWithTimeout creates a new GetV1GovProposalsProposalIDDepositsParams object
// with the ability to set a timeout on a request.
func NewGetV1GovProposalsProposalIDDepositsParamsWithTimeout(timeout time.Duration) *GetV1GovProposalsProposalIDDepositsParams {
	return &GetV1GovProposalsProposalIDDepositsParams{
		timeout: timeout,
	}
}

// NewGetV1GovProposalsProposalIDDepositsParamsWithContext creates a new GetV1GovProposalsProposalIDDepositsParams object
// with the ability to set a context for a request.
func NewGetV1GovProposalsProposalIDDepositsParamsWithContext(ctx context.Context) *GetV1GovProposalsProposalIDDepositsParams {
	return &GetV1GovProposalsProposalIDDepositsParams{
		Context: ctx,
	}
}

// NewGetV1GovProposalsProposalIDDepositsParamsWithHTTPClient creates a new GetV1GovProposalsProposalIDDepositsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1GovProposalsProposalIDDepositsParamsWithHTTPClient(client *http.Client) *GetV1GovProposalsProposalIDDepositsParams {
	return &GetV1GovProposalsProposalIDDepositsParams{
		HTTPClient: client,
	}
}

/* GetV1GovProposalsProposalIDDepositsParams contains all the parameters to send to the API endpoint
   for the get v1 gov proposals proposal ID deposits operation.

   Typically these are written to a http.Request.
*/
type GetV1GovProposalsProposalIDDepositsParams struct {

	/* Limit.

	   Page size
	*/
	Limit *float64

	/* Page.

	   Page number
	*/
	Page *float64

	/* ProposalID.

	   Proposal id
	*/
	ProposalID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 gov proposals proposal ID deposits params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1GovProposalsProposalIDDepositsParams) WithDefaults() *GetV1GovProposalsProposalIDDepositsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 gov proposals proposal ID deposits params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1GovProposalsProposalIDDepositsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithTimeout(timeout time.Duration) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithContext(ctx context.Context) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithHTTPClient(client *http.Client) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithLimit(limit *float64) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetLimit(limit *float64) {
	o.Limit = limit
}

// WithPage adds the page to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithPage(page *float64) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetPage(page *float64) {
	o.Page = page
}

// WithProposalID adds the proposalID to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) WithProposalID(proposalID string) *GetV1GovProposalsProposalIDDepositsParams {
	o.SetProposalID(proposalID)
	return o
}

// SetProposalID adds the proposalId to the get v1 gov proposals proposal ID deposits params
func (o *GetV1GovProposalsProposalIDDepositsParams) SetProposalID(proposalID string) {
	o.ProposalID = proposalID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1GovProposalsProposalIDDepositsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit float64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatFloat64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage float64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatFloat64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	// path param proposalId
	if err := r.SetPathParam("proposalId", o.ProposalID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
