// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1MempoolParams creates a new GetV1MempoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1MempoolParams() *GetV1MempoolParams {
	return &GetV1MempoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1MempoolParamsWithTimeout creates a new GetV1MempoolParams object
// with the ability to set a timeout on a request.
func NewGetV1MempoolParamsWithTimeout(timeout time.Duration) *GetV1MempoolParams {
	return &GetV1MempoolParams{
		timeout: timeout,
	}
}

// NewGetV1MempoolParamsWithContext creates a new GetV1MempoolParams object
// with the ability to set a context for a request.
func NewGetV1MempoolParamsWithContext(ctx context.Context) *GetV1MempoolParams {
	return &GetV1MempoolParams{
		Context: ctx,
	}
}

// NewGetV1MempoolParamsWithHTTPClient creates a new GetV1MempoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1MempoolParamsWithHTTPClient(client *http.Client) *GetV1MempoolParams {
	return &GetV1MempoolParams{
		HTTPClient: client,
	}
}

/* GetV1MempoolParams contains all the parameters to send to the API endpoint
   for the get v1 mempool operation.

   Typically these are written to a http.Request.
*/
type GetV1MempoolParams struct {

	/* Account.

	   Account address
	*/
	Account *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 mempool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1MempoolParams) WithDefaults() *GetV1MempoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 mempool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1MempoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 mempool params
func (o *GetV1MempoolParams) WithTimeout(timeout time.Duration) *GetV1MempoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 mempool params
func (o *GetV1MempoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 mempool params
func (o *GetV1MempoolParams) WithContext(ctx context.Context) *GetV1MempoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 mempool params
func (o *GetV1MempoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 mempool params
func (o *GetV1MempoolParams) WithHTTPClient(client *http.Client) *GetV1MempoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 mempool params
func (o *GetV1MempoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the get v1 mempool params
func (o *GetV1MempoolParams) WithAccount(account *string) *GetV1MempoolParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the get v1 mempool params
func (o *GetV1MempoolParams) SetAccount(account *string) {
	o.Account = account
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1MempoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Account != nil {

		// query param account
		var qrAccount string

		if o.Account != nil {
			qrAccount = *o.Account
		}
		qAccount := qrAccount
		if qAccount != "" {

			if err := r.SetQueryParam("account", qAccount); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
