// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TendermintP2pProtocolVersion tendermint p2p protocol version
//
// swagger:model tendermint.p2p.ProtocolVersion
type TendermintP2pProtocolVersion struct {

	// app
	App string `json:"app,omitempty"`

	// block
	Block string `json:"block,omitempty"`

	// p2p
	P2p string `json:"p2p,omitempty"`
}

// Validate validates this tendermint p2p protocol version
func (m *TendermintP2pProtocolVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tendermint p2p protocol version based on context it is used
func (m *TendermintP2pProtocolVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TendermintP2pProtocolVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TendermintP2pProtocolVersion) UnmarshalBinary(b []byte) error {
	var res TendermintP2pProtocolVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
