// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/lidofinance/terra-fcd-rest-client/columbus-5/models"
)

// NewSimulateParams creates a new SimulateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSimulateParams() *SimulateParams {
	return &SimulateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSimulateParamsWithTimeout creates a new SimulateParams object
// with the ability to set a timeout on a request.
func NewSimulateParamsWithTimeout(timeout time.Duration) *SimulateParams {
	return &SimulateParams{
		timeout: timeout,
	}
}

// NewSimulateParamsWithContext creates a new SimulateParams object
// with the ability to set a context for a request.
func NewSimulateParamsWithContext(ctx context.Context) *SimulateParams {
	return &SimulateParams{
		Context: ctx,
	}
}

// NewSimulateParamsWithHTTPClient creates a new SimulateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSimulateParamsWithHTTPClient(client *http.Client) *SimulateParams {
	return &SimulateParams{
		HTTPClient: client,
	}
}

/* SimulateParams contains all the parameters to send to the API endpoint
   for the simulate operation.

   Typically these are written to a http.Request.
*/
type SimulateParams struct {

	// Body.
	Body *models.CosmosTxV1beta1SimulateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the simulate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimulateParams) WithDefaults() *SimulateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the simulate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimulateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the simulate params
func (o *SimulateParams) WithTimeout(timeout time.Duration) *SimulateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the simulate params
func (o *SimulateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the simulate params
func (o *SimulateParams) WithContext(ctx context.Context) *SimulateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the simulate params
func (o *SimulateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the simulate params
func (o *SimulateParams) WithHTTPClient(client *http.Client) *SimulateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the simulate params
func (o *SimulateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the simulate params
func (o *SimulateParams) WithBody(body *models.CosmosTxV1beta1SimulateRequest) *SimulateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the simulate params
func (o *SimulateParams) SetBody(body *models.CosmosTxV1beta1SimulateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SimulateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
