// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerraOracleV1beta1QueryVoteTargetsResponse QueryVoteTargetsResponse is response type for the
// Query/VoteTargets RPC method.
//
// swagger:model terra.oracle.v1beta1.QueryVoteTargetsResponse
type TerraOracleV1beta1QueryVoteTargetsResponse struct {

	// vote_targets defines a list of the denomination in which everyone
	// should vote in the current vote period.
	VoteTargets []string `json:"vote_targets"`
}

// Validate validates this terra oracle v1beta1 query vote targets response
func (m *TerraOracleV1beta1QueryVoteTargetsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this terra oracle v1beta1 query vote targets response based on context it is used
func (m *TerraOracleV1beta1QueryVoteTargetsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TerraOracleV1beta1QueryVoteTargetsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerraOracleV1beta1QueryVoteTargetsResponse) UnmarshalBinary(b []byte) error {
	var res TerraOracleV1beta1QueryVoteTargetsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
