// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerraTreasuryV1beta1QuerySeigniorageProceedsResponse QuerySeigniorageProceedsResponse is response type for the
// Query/SeigniorageProceeds RPC method.
//
// swagger:model terra.treasury.v1beta1.QuerySeigniorageProceedsResponse
type TerraTreasuryV1beta1QuerySeigniorageProceedsResponse struct {

	// seigniorage proceeds
	SeigniorageProceeds string `json:"seigniorage_proceeds,omitempty"`
}

// Validate validates this terra treasury v1beta1 query seigniorage proceeds response
func (m *TerraTreasuryV1beta1QuerySeigniorageProceedsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this terra treasury v1beta1 query seigniorage proceeds response based on context it is used
func (m *TerraTreasuryV1beta1QuerySeigniorageProceedsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TerraTreasuryV1beta1QuerySeigniorageProceedsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerraTreasuryV1beta1QuerySeigniorageProceedsResponse) UnmarshalBinary(b []byte) error {
	var res TerraTreasuryV1beta1QuerySeigniorageProceedsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
